--- #YAML:1.0
name:                Encode-Bootstring
version:             0.01
abstract:            Encode and decode utf8 into a set of basic code points
license:             perl
author:              
    - Soren Dossing <netcom@sauber.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
